[package]
name = "windows-common-dialog"
version = "0.1.0"
edition = "2024"
authors = ["Mimimishkin <printf.mika@gmail.com>"]
description = "Wrapper for Windows file chooser dialog with files&folders mode"
license = "MIT"
repository = "https://github.com/mimimishkin/windows-common-dialog"
readme = "README.md"
keywords = ["windows", "dialog"]
categories = ["gui", "os::windows-apis"]

[dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Storage_EnhancedStorage",
    "Win32_System_Com",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Ole",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell_Common",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = "0.62.2"
windows-registry = "0.6.1"
